apiVersion: apps/v1
kind: Deployment
metadata:
  name: dhnmrt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dhnmrt
  template:
    metadata:
      labels:
        app: dhnmrt
    spec:
      containers:
      - image: okteto.dev/dhnmrt:latest
        name: dhnmrt
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "af4e77d9-3a09-4e9a-a23f-f0c21cf2797a"
        - name: Vless_Path
          value: "/vl5df55"
        - name: Vmess_UUID
          value: "af4e77d9-3a09-4e9a-a23f-f0c21cf2797a"
        - name: Vmess_Path
          value: "/v4m66fg6"
        - name: Share_Path
          value: "/v2link"
